name: "preprocess_py"
backend: "python"
max_batch_size: 8

input [
  { 
    name: "raw_input", 
    data_type: TYPE_INT32, 
    dims: [ -1, -1 ]
  }
]

output [
  { 
    name: "out_feats", 
    data_type: TYPE_INT32, 
    dims: [ -1 ]
  }
]

instance_group [
  { 
    kind: KIND_CPU, 
    count: 1
  }
]

parameters {
  key: "feature_dim"
  value: { string_value: "16" }
}

parameters {
  key: "vocab_size"
  value: { string_value: "10000" }
}
